---
# Kibana backend configuration
kibana_backend_host: "{{ hostvars[groups['kibana'][0]]['inventory_hostname'] }}"
kibana_backend_port: "5601"
kibana_backend_protocol: "https"

# Nginx configuration
nginx_worker_processes: "auto"
nginx_worker_connections: "1024"
nginx_client_max_body_size: "10m"

# SSL configuration
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384" 