---
- name: Fetch CA certificate from es_ca_node
  ansible.builtin.fetch:
    src: "{{ es_ca_cert }}"
    dest: /tmp/ca.crt
    flat: yes
  delegate_to: "{{ es_ca_node }}"
  vars:
    es_ca_node: "{{ groups['es_nodes'][0] }}"
    es_ca_cert: "/etc/elasticsearch/certs/ca.crt"


- name: Create certificates directory for Kibana
  ansible.builtin.file:
    path: "{{ certificates_dir_kibana }}"
    state: directory
    mode: '0750'
    owner: kibana
    group: kibana

- name: Copy CA certificate to Kibana nodes
  ansible.builtin.copy:
    src: /tmp/ca.crt
    dest: "{{ ca_cert_kibana }}"
    mode: '0640'
    owner: kibana
    group: kibana

- name: Include API key configuration tasks
  ansible.builtin.include_tasks: api_key_config.yml
  when: use_api_key_auth | default(true)

- name: Generate private key for Kibana HTTPS
  ansible.builtin.command: >
    openssl genrsa -out {{ certificates_dir_kibana }}/kibana-server.key 2048
  args:
    creates: "{{ certificates_dir_kibana }}/kibana-server.key"

- name: Set ownership and permissions for Kibana private key
  ansible.builtin.file:
    path: "{{ certificates_dir_kibana }}/kibana-server.key"
    owner: kibana
    group: kibana
    mode: '0600'

- name: Generate certificate signing request for Kibana
  ansible.builtin.command: >
    openssl req -new -key {{ certificates_dir_kibana }}/kibana-server.key 
    -out {{ certificates_dir_kibana }}/kibana-server.csr 
    -subj "/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN={{ inventory_hostname }}"
  args:
    creates: "{{ certificates_dir_kibana }}/kibana-server.csr"

- name: Create certificate extensions file for Kibana
  ansible.builtin.copy:
    content: |
      [v3_req]
      subjectAltName=DNS:localhost,DNS:{{ inventory_hostname }},IP:{{ inventory_hostname }}
    dest: "{{ certificates_dir_kibana }}/kibana-server.ext"
    mode: '0644'
    owner: kibana
    group: kibana

- name: Generate self-signed certificate for Kibana HTTPS
  ansible.builtin.command: >
    openssl x509 -req -in {{ certificates_dir_kibana }}/kibana-server.csr 
    -signkey {{ certificates_dir_kibana }}/kibana-server.key 
    -out {{ certificates_dir_kibana }}/kibana-server.crt 
    -days 365 
    -extensions v3_req 
    -extfile {{ certificates_dir_kibana }}/kibana-server.ext
  args:
    creates: "{{ certificates_dir_kibana }}/kibana-server.crt"

- name: Set ownership and permissions for Kibana certificate
  ansible.builtin.file:
    path: "{{ certificates_dir_kibana }}/kibana-server.crt"
    owner: kibana
    group: kibana
    mode: '0644'

- name: Remove certificate signing request file
  ansible.builtin.file:
    path: "{{ certificates_dir_kibana }}/kibana-server.csr"
    state: absent

- name: Remove certificate extensions file
  ansible.builtin.file:
    path: "{{ certificates_dir_kibana }}/kibana-server.ext"
    state: absent

- name: Open Kibana ports in firewalld
  ansible.builtin.command: >
    firewall-cmd --permanent --add-port={{ kibana_port }}/tcp
  become: true

- name: Configure Kibana
  ansible.builtin.template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: '0644'
    owner: kibana
    group: kibana
  notify: restart kibana

  

- name: Ensure /usr/share/kibana ownership
  ansible.builtin.file:
    path: /usr/share/kibana
    owner: kibana
    group: kibana
    recurse: yes
  become: true

- name: Ensure /var/log/kibana directory exists and is owned by kibana
  ansible.builtin.file:
    path: /var/log/kibana
    state: directory
    owner: kibana
    group: kibana
    mode: '0750'
    recurse: yes

- name: Start Kibana service
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: yes
