---
- name: Ensure Java is installed
  ansible.builtin.yum:
    name: "{{ java_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
  tags:
    - install
    - dependencies

