---
- name: Deploy Nginx Reverse Proxy
  hosts: nginx
  become: true
  gather_facts: true
  
  roles:
    - nginx

  post_tasks:
    - name: Wait for nginx service to be ready
      ansible.builtin.wait_for:
        port: 443
        host: "{{ inventory_hostname }}"
        delay: 5
        timeout: 30
      
    - name: Test nginx health check
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}/nginx-health"
        method: GET
        validate_certs: no
        return_content: yes
      register: health_check
      failed_when: "'healthy' not in health_check.content"
      
    - name: Display nginx status
      ansible.builtin.debug:
        msg: 
          - "Nginx reverse proxy is running successfully!"
          - "Access Kibana via HTTPS: https://{{ inventory_hostname }}"
          - "Local access via port forwarding: https://localhost:8443"
          - "Health check response: {{ health_check.content | trim }}" 
