---
- name: Configuring and Deploying ElasticSearch node
  hosts: es_cluster
  become: yes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 8.9.0
    es_config:
      node.name: "{{ es_node_name }}"
      cluster.name: "my-es-cluster"
      network.host: "0.0.0.0"
      http.port: 9200
      xpack.security.enabled: true
      bootstrap.memory_lock: true
    es_heap_size: 2g

  tasks:
    - name: Set memlock soft limit for elasticsearch user
      lineinfile:
        path: /etc/security/limits.conf
        line: "elasticsearch soft memlock unlimited"
        state: present

    - name: Set memlock hard limit for elasticsearch user
      lineinfile:
        path: /etc/security/limits.conf
        line: "elasticsearch hard memlock unlimited"
        state: present

    - name: Create systemd override directory for elasticsearch service
      file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        mode: '0755'

    - name: Configure systemd LimitMEMLOCK for elasticsearch service
      copy:
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf
        content: |
          [Service]
          LimitMEMLOCK=infinity
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted
